### ISSUE TITLE
slash vs dash (IATI vs PublicBodies); "aggregator conflict"

### ISSUE THREAD

**Issue by VladimirAlexiev** [IATI/IATI-Codelists-NonEmbedded#152]
The "slash vs underscore" issue (split off from https://github.com/okfn/publicbodies/issues/74) reflects a big difference in philosophy, so I believe it merits a new issue to be opened.
- IATI has mostly been used in XML exchanges where URLs are not used. @rory09 can you elaborate why having a slash in the ID will harm this goal "wanting the identifier to be easily inserted into a url as is, given the variety". 
- PublicBodies is driven by newer COOLURI trends, in particular "hackability" (removing some suffixes of the URL still produces useful URLs). Eg http://publicbodies.org/eu/dg-infso is one directorate, while http://publicbodies.org/eu is the list of all EU orgs known to PublicBodies.

If we register OpenCorporates (who have info on 127M companies) as XI-OC in IATI, we'll have a similar issue:
- IATI will want to represent https://opencorporates.com/companies/ro/23187766 as XI-OC-ro-23187766  (change slash to underscore or dash)

Since there is no RO prefix in IATI (and maybe the official RO registry is not yet openly available), XI-OC-ro would be a very useful prefix.

And this raises a bigger issue (@CountCulture), consider 
http://data.companieshouse.gov.uk/doc/company/07444723, which is the same entity as
https://beta.companieshouse.gov.uk/company/07444723 and also
https://opencorporates.com/companies/gb/07444723.

The GB official register is online and registered in IATI.
So one should prefer GB-COH-07444723 to XI-OC-gb-07444723.
But does this mean when an official register becomes available, we should deprecate "aggregator" identifier schemes or URLs (like OpenCorporates or PublicBodies) in favor of that official register?

**Comment by timgdavies** [comment]
@VladimirAlexiev The org-id.guide methodology includes the idea of a 'primary' register and always prefers these over secondary aggregations.

XI-OC is unlikely to ever be created as a register/organisation identifier list, as it simply republishes information from existing registers - so in all the cases that there is an identifier in Open Corporates, it should be possible to cross-reference it to an official register, and publish it as such. 

The use of the codes (GB-COH) rather than URIs, is so that users can choose which endpoint to resolve an identifier against, and to be robust against changes in URI patterns.

(E.g., faced with GB-COH-07444723, with the meta-data available in [org-id.guide](http://org-id.guide/list/GB-COH) the user could choose to resolve against Open Corporates data at https://opencorporates.com/companies/gb/07444723 or Companies House data at http://data.companieshouse.gov.uk/doc/company/07444723)

**Comment by VladimirAlexiev** [comment]
Ok, got it. But:
- the metadata doesn't include URL patterns. As you see above, COH have 2 patterns; and often there may be different prefixes for machine-readable data vs human-readable page.
- your description doesn't allow for company URLs to be created and used since it says "the user could choose". IATI prefixes COULD be used as part of permanent URL schemes but since they don't give specific guidance what URL templates to choose, they WON'T be used in permanent URLs.

Given that linked data / semantic web is now the predominant way of doing inter-enterprise data integration, would't it be nice for IATI to think of permanent URLs?

**Comment by timgdavies** [comment]
> The metadata doesn't include URL patterns. As you see above, COH have 2 patterns; and often there may be different prefixes for machine-readable data vs human-readable page.

Happy to look at getting this included. If you can suggest best way to capture this, we could add to the schema for org-id.guide meta-data. 

> Given that linked data / semantic web is now the predominant way of doing inter-enterprise data integration, would't it be nice for IATI to think of permanent URLs?

@VladimirAlexiev I'm not sure that is true. 

Whilst getting the second part of a URI standardised well may be possible - experience suggests that getting agreement on using the same domain - or maintenance of dereferenceable URIs at a particular location - is far from easy, and tends to undermine attempts to use URIs for data integration across distributed publication.

**Comment by VladimirAlexiev** [comment]
Wikidata has 3 such props:
- formatterURL (https://www.wikidata.org/wiki/Property:P1921), eg `https://viaf.org/viaf/$1`
- RDF URI template (https://www.wikidata.org/wiki/Property:P3303), eg `http://www.idref.fr/$1/id`
- third-party formatter URL (https://www.wikidata.org/wiki/Property:P1630), eg `http://www.bbc.co.uk/music/artists/$1` for MusicBrainz (BBC uses that database)

> getting agreement is far from easy

That seems like a bad excuse not to try it. There are many successful examples where this has happened, eg
- VIAF has 20M entities (15M people) from 30 contributors (20 national libraries)
- Wikidata has 20M entities (but few companies, maybe 300k), and may soon be recommended for use in schema.org data
- EN wikipedia & DBpedia have 5M entities, and these are used very widely

If you have several URLs for an entity, `owl:sameAs` can be used to declare them equivalent

**Comment by VladimirAlexiev** [comment]
> identifier in Open Corporates, it should be possible to cross-reference it to an official register, and publish it as such.

And when the particular national register is not online, still use the OC site in formatterURL? That's a good idea.

**Comment by benparkergit** [comment]
OpenCorporates only publishes records that are already online in one format
or another.

Regards

Ben


On Mon, May 22, 2017 at 10:29 AM, Vladimir Alexiev <notifications@github.com

**Comment by hayfield** [comment]
@IATI/bas Is this resolved by the org-id changes?

**Comment by VladimirAlexiev** [comment]
>OpenCorporates only publishes records that are already online in one format or another.

That is not entirely true. Many registers publish data in weird non-user-friendly and non-web-friendly ways, while @openc makes that data uniformly available. Eg the BG register hides companies behind MS.NET postbacks and CAPTCHA. Also, there aren't company page URLs including the official ID. There are pages keyed by an ugly GUID (eg https://public.brra.bg/CheckUps/Verifications/ActiveCondition.ra?guid=617f4edf8c154f4296efdf146513de21 for EIK=204060254) and even these are behind CAPTCHA.

@openc doesn't yet have the BG register online but hopefully will soon, as part of @eubusinessgraph. The full data is dumped at http://opendata.government.bg/dataset/tbprobckn-pernctbp, we've analyzed it and a simple version is at http://data.businessgraph.io, eg see http://data.businessgraph.io/resource?uri=http://data.businessgraph.io/company/BG/200356710

**Comment by amy-silcock** [comment]
IATI follows the guidance provide by org-id.guide. I am closing the issue on the IATI github. 

The org-id GitHub is here: https://github.com/org-id/register/issues
