### ISSUE TITLE
Finance Type - non flow items

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists-NonEmbedded#16]
The OECD DAC Codelist "Type of Finance" now\* includes:

![image](https://cloud.githubusercontent.com/assets/1209944/3174992/1c4f40cc-ebf7-11e3-9806-a8e08417324d.png)

@bill-anderson - should these be added to `FinanceType` ?

(*Codelist source: http://www.oecd.org/dac/stats/documentupload/Codelist04042014.xls | accessed 4 June, 15:48)

**Comment by amy-silcock** [comment]
DAC codelists have been updated since 2014. If there's an outstanding issue needing an IATI upgrade please add the proposal to Discuss: https://discuss.iatistandard.org/c/standard-management
