### ISSUE TITLE
Add code ET-MOT to OrganisationRegistrationAgency codelist

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Codelists-NonEmbedded#170]
See: https://discuss.iatistandard.org/t/approved-proposed-addition-to-the-organisation-registration-agency-codelist-ethiopia/941

**Comment by hayfield** [comment]
Added in https://github.com/IATI/IATI-Codelists-NonEmbedded/commit/3d66c5fb8aa6ee01d25dc22a03a0b6f5c48f58f6
