### ISSUE TITLE
Remove OrganisationIdentifier from versions up to 1.04

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists-NonEmbedded#176]
Discussion here: https://discuss.iatistandard.org/t/why-does-2-02-include-a-code-list-that-was-not-supported-since-1-04/1101/

**Comment by andylolz** [comment]
Issue title should read “since 1.04”.

Big +1 for removing this codelist completely forever.

**Comment by andylolz** [comment]
By the sounds of it, the proposal is now to remove the codelist from ALL versions :tada::tada::tada:

**Comment by amy-silcock** [comment]
Closing, because: Following IATI’s standard management procedures we currently can’t remove a non-embedded codelist.
