### ISSUE TITLE
TagVocabulary: Add Codes

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Codelists-NonEmbedded#178]
**NOTE:** This Codelist does not currently exist. There is a separate issue (#183) to make it be a thing.

Make the following changes to the TagVocabulary Codelist:

**Add Code:**

- [x] Code: `1`
  - [x] Name: `Agrovoc`
  - [x] Description: ` A controlled vocabulary covering all areas of interest of the Food and Agriculture Organization (FAO) of the United Nations, including food, nutrition, agriculture, fisheries, forestry, environment etc`
  - [x] URL: `http://artemide.art.uniroma2.it:8081/agrovoc/agrovoc/en/`
- [x] Code: `99`
  - [x] Name: `Reporting Organisation`

**Comment by hayfield** [comment]
Need to see how the changes from https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/10 impact this issue.

**Comment by allthatilk** [comment]
Question resolved: Agreed `99` code should be added.

**Comment by hayfield** [comment]
Fixed by #188
