### ISSUE TITLE
ResultVocabulary: Add Codes

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Codelists-NonEmbedded#181]
**NOTE:** This Codelist does not currently exist. There is a separate issue (#183) to make it be a thing.

Make the following changes to the ResultVocabulary Codelist:

**Add Code:**

- [x] Code: `99`
  - [x] Name: `Reporting Organisation`

**Comment by hayfield** [comment]
Need to see how the changes from https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/10 impact this issue.

**Comment by allthatilk** [comment]
Question resolved: No `98` codes on new codelists.

**Comment by hayfield** [comment]
Fixed by #188

**Comment by amy-silcock** [comment]
Updated codelist is here: http://reference.iatistandard.org/203/codelists/ResultVocabulary/
