### ISSUE TITLE
OrganisationType: Add Codes

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Codelists-NonEmbedded#182]
Update OrganisationType Codelist to include:

**Codes to add:**
- [x] Code `11`
  - [x] Name: `Local Government`
  - [x] Description: `Any local (sub national) government organisation in either donor or recipient country.`
- [x] Code `24`
  - [x] Name: `Partner Country based NGO`
  - [x] Description: `Partner country based NGO- NGOs not based in an aid recipient country and carrying out operations in one or more aid recipient countries.`
- [x] Code `71`
  - [x] Name: `Private Sector in Provider Country`
  - [x] Description: `Is in provider / donor country.`
- [x] Code `72`
  - [x] Name: `Private Sector in Aid Recipient Country`
  - [x] Description: `Is in aid recipient country.`
- [x] Code `73`
  - [x] Name: `Private Sector in Third Country`
  - [x] Description: `Is not in either a donor or aid recipient country.`
- [x] Code `90`
  - [x] Name: `Other`

**Comment by PetyaKangalova** [comment]
Clarifying question was asked about this proposal on [IATI Discuss](https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/21). With the addition of new codes to the OrganisationType codelist, questions were raised about the meaning of the new codes.

To avoid confusion and for clarity, could the below descriptions be added to the relevant new codes? The decriptions are taken from the [mapping spreadsheet ](https://docs.google.com/spreadsheets/d/1UQ8oPyGiBSzY64UO0CBnH4hND9D2d0MkZ07FRYGhrjM/edit#gid=0)that was shared during the discussion for this proposal- see in [here](https://discuss.iatistandard.org/t/organisation-type-codes-additions-included-2-03/858/14).


- 11 Local Government- Any local (sub national) government organisation in either donor or recipient country
- 24 Partner country based NGO- NGOs not based in an aid recipient country and carrying out operations in one or more aid recipient countries
- 71 Private Sector in Provider Country- Is in provider /donor country
- 72 Private Sector in Aid Recipient Country- Is in aid recipient country
- 73 Private Sector in Third Country- Is not in either a donor or aid recipient country
- 90 Other

Let me know if there are any questions and either myself or @wendyrogers can clarify.

**Comment by hayfield** [comment]
This Codelist is now in the NE repo https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/210

**Comment by hayfield** [comment]
Descriptions from https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/182#issuecomment-349712613 have been added to the main post

**Comment by hayfield** [comment]
With the name of `Private Sector in Third Country`... this reads as if there are a first and second country in some manner.

Should it be `Third Party` or `Third World` or `Third Place` or something else?

**Comment by wendyrogers** [comment]
Language taken directly from and to align with DAC channel codes @hayfield and description should confirm meaning eg not donor or recipient country

**Comment by hayfield** [comment]
Name being left as-is because this is the wording from the DAC.

**Comment by amy-silcock** [comment]
Current updated descriptions are here: http://reference.iatistandard.org/203/codelists/OrganisationType/
