### ISSUE TITLE
Add new Codelists with 2.03

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Codelists-NonEmbedded#183]
Create the following empty Codelists with `2.03` (adding the Codes themselves are separate issues):

**Add new Codelists:**

- [x] BudgetNotProvided
- [x] AidTypeVocabulary
- [x] ResultVocabulary
- [x] TagVocabulary

**Add complete:**

- [x] BudgetNotProvided
- [x] AidTypeVocabulary
- [x] ResultVocabulary
- [x] TagVocabulary

**Add descriptions:**

- [x] BudgetNotProvided
- [x] AidTypeVocabulary
- [x] ResultVocabulary
- [x] TagVocabulary

**Comment by hayfield** [comment]
Need to see how the changes from https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/13 impact this issue.

**Comment by allthatilk** [comment]
@IATI/bas Can we get an update on this one please?

**Comment by allthatilk** [comment]
Marked as incomplete while questions pending.

**Comment by amy-silcock** [comment]
All now have descriptions in English on the internal summary table

All 4 codelists are complete

**Comment by amy-silcock** [comment]
You can see the codelists here: http://reference.iatistandard.org/203/codelists/ResultVocabulary/
