### ISSUE TITLE
BudgetNotProvided: Add Codes

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Codelists-NonEmbedded#184]
**Note:** This Codelist does not currently exist. A separate issue (#183) has been created for that.

**Codes to add:**
- [x] Code `1`
  - [x] Name: `Commercial Restrictions`
- [x] Code `2`
  - [x] Name: `Legal Restrictions`
- [x] Code `3`
  - [x] Name: `Rapid Onset Emergency`

**Comment by hayfield** [comment]
#188 added these codes, though the capitalisation is different

**Comment by amy-silcock** [comment]
Changes can be seen here: http://reference.iatistandard.org/203/codelists/BudgetNotProvided/
