### ISSUE TITLE
GLIDE codelist is down

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists-NonEmbedded#239]
Being discussed here: https://discuss.iatistandard.org/t/help-cant-access-glide-numbers/1225

This might need a fix in terms of the URL posted on the HumanitarianScopeVocabulary codelist

cc/ @davidmegginson

**Comment by stevieflow** [comment]
So this is back up - I'll close

**Comment by andylolz** [comment]
I set up monitoring a while ago, and it’s still having (weekly?) wobbles.
