### ISSUE TITLE
Deprecate the BudgetIdentifier codelist (v2.03 upgrade)

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists-NonEmbedded#241]
This is from the [IATI Standards Day notes](https://docs.google.com/spreadsheets/d/1RRE5IjyirIp-JFRF94JUNL6IEKnEU42uGzlWoj1yJ0A/edit#gid=0):

> _Proposal_: Deprecate the BudgetIdentifier codelist
>
> _Outcome_: **Accept**
>
> _Discussion_: Consensus as codelist has been replaced by expanded CRS Purpose codes

I’m not sure how this is done in practice. The [OrganisationIdentifier](http://iatistandard.org/202/codelists/OrganisationIdentifier/) example suggests it’s just a case of modifying the codelist description. Does that sound sufficient?

**Comment by amy-silcock** [comment]
The description on the codelist says "As of version 2.03 this codelist has been deprecated"

**Comment by andylolz** [comment]
> The description on the codelist says "As of version 2.03 this codelist has been deprecated"

Great – looks like this was addressed in #257.
