### ISSUE TITLE
Fix OrganisationRegistrationAgency codelist description

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists-NonEmbedded#248]
The [OrganisationRegistrationAgency codelist description](https://github.com/IATI/IATI-Codelists-NonEmbedded/blob/70e246d3a2916f060a3736a8ed321befedf54d13/xml/OrganisationRegistrationAgency.xml#L6-L14) includes the following sentence:

> IATI replicates the list directly from org-id.guide with the exception of the XI-IATI codelist.

I think this may be incorrect for two reasons:

 * I don’t think IATI replicates the list from [org-id.guide](http://org-id.guide). The IATI list has only been updated a couple of times since the switchover. I’ve created an issue (#235) and sent a one-off pull request to address that (#247) but I suppose keeping the lists in sync longterm is related to #172.
 * I’m not sure what the “with the exception of the XI-IATI codelist” bit means. The `XI-IATI` code [is included on org-id.guide](http://org-id.guide/list/XI-IATI), and the [IATI OrganisationRegistrationAgency codelist](https://github.com/IATI/IATI-Codelists-NonEmbedded/blob/70e246d3a2916f060a3736a8ed321befedf54d13/xml/OrganisationRegistrationAgency.xml#L975-L985).

@timgdavies already made the first point just here: https://github.com/andylolz/org-id-finder/issues/6#issuecomment-363868555, and the second point just here: https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/166#discussion_r128591000

**Comment by stevieflow** [comment]
Thanks @andylolz 

I'd written some updated description text for this list, in the assumption that the synch/update with org-id wil lbe put in place

See https://github.com/stevieflow/IATI-Codelists-NonEmbedded/commit/fc413c645b09b0cf634d0deac39abdfdcaeacb69 - but here's the text anyway - 

Im also minded that should we accept this update, it will need to be updated across different versions 

> The values from this codelist are used to identify the particular list that an organisation identifier was drawn from. The codelist provides a register of known identifier lists, including national company registers, NGO directories and international and multilateral organisation lists - along with guidance and online resources to help locate the identifiers assigned to a specific organisation. 
> 
> As of 17 July 2017 this list is maintained by the org-id.guide project. Data publishers can now search for and locate the relevant  list for a particular organisation identifier using the org-id website. The full register of identifier sources is also available to download in XML, JSON and CSV format. 
> 
> IATI periodically replicates the codelist of identifier sources from org-id.guide, to assist those accessing IATI documentation.  However, it is advised that the most up-to-date source is the org-id.guide project
> 
> If org-id.guide does not contain an entry for the kind of organisation you need to identify, you can make a request a new list is included in the register following the guidance at http://docs.org-id.guide/en/latest/contribute/ or by getting in touch with contact@org-id.guide.

**Comment by andylolz** [comment]
> in the assumption that the synch/update with org-id wil lbe put in place

I don’t think we should assume this. I think this needs bottoming out before revising the wording.

> However, it is advised that the most up-to-date source is the org-id.guide project

See Tim’s comment about “org-id.guide project”: https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/166#discussion_r128591288

> it will need to be updated across different versions

Yes… But since non-embedded codelists are the same across all versions, this should Just Happen™ on deployment.
