### ISSUE TITLE
Some IATI codelist vocabularies point to external lists rather than the IATI replicated ones.

### ISSUE THREAD

**Issue by amy-silcock** [IATI/IATI-Codelists-NonEmbedded#293]
URLs are to be changed in:

[Aid Type Vocab](http://reference.iatistandard.org/codelists/AidTypeVocabulary/)
[Geographic Vocab](http://reference.iatistandard.org/codelists/GeographicVocabulary/)
[Policy Marker Vocab](http://reference.iatistandard.org/codelists/PolicyMarkerVocabulary/)
[Region Vocab](http://reference.iatistandard.org/codelists/RegionVocabulary/)
[Sector Vocab](http://reference.iatistandard.org/codelists/SectorVocabulary/)

Replicated codelists can contain values that have been withdrawn from external codelists. Therefore IATI codelist vocabs should point to the IATI replicated codelist where relevant, rather than the external URL.

**Comment by andylolz** [comment]
I guess this is the same as (or very similar to?) #272.

**Comment by amy-silcock** [comment]
The change has been merged and deployed
