### ISSUE TITLE
Update DAC codelists according to July 2019 changes and February 2020 changes

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists-NonEmbedded#301]
DAC CRS codelists were updated on 23/07/19. See:
http://www.oecd.org/dac/financing-sustainable-development/development-finance-topics/crs-xml.htm

Replicated codelists should be updated accordingly.

**Comment by andylolz** [comment]
The process for getting replicated codelist changes into the standard was previously documented here:
https://github.com/IATI/IATI-Extra-Documentation/blob/9c54e586/en/codelists-guides/codelist-management.rst#updates-to-non-embedded-codelists

I don’t know if this process has changed, but it’s no longer documented:
http://reference.iatistandard.org/203/codelists-guides/codelist-management/#non-embedded-codelists-replicated

**Comment by samuele-mattiuzzo** [comment]
@andylolz we need to do a bit of looking up as to why some withdrawn codes are missing on the reference site and also check for the new updates. 
Earliest we can do that is Friday, so this will be taken care of at the end of this week or early next week. Thank you!

**Comment by andylolz** [comment]
Hi @samuele-mattiuzzo – That’s great to hear. Thanks for letting me know, and thanks for looking into this.

**Comment by andylolz** [comment]
DAC codelists were updated again on 28/02/20. See:
http://www.oecd.org/development/financing-sustainable-development/development-finance-standards/dacandcrscodelists.htm

**Comment by PetyaKangalova** [comment]
Thanks @andylolz . Linking to the [pull request](https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/326/files#diff-14f0f55b5d186317d078771305bd88ce) for this that I will be reviewing next week.

**Comment by andylolz** [comment]
Great! Thanks for the update, @PetyaKangalova.

I can see a few issues with the pull request (most notably, that automated checks are failing). Would it be helpful for me to provide comments there?

**Comment by PetyaKangalova** [comment]
@andylolz , yes that will be great! Thanks ! @akmiller01

**Comment by akmiller01** [comment]
Looks like we will need to strip out some of those extraneous OECD-specific attributes @PetyaKangalova . Half of the XML lint errors are along the lines of:

`xml/CRSChannelCode.xml:26: element codelist-item: Schemas validity error : Element 'codelist-item', attribute 'mcd': The attribute 'mcd' is not allowed.`

**Comment by andylolz** [comment]
Here’s a list of the steps I went through when I previously updated from DAC XML:
https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/283#issuecomment-457626235

The second step in there is about removing these invalid DAC namespace elements. I can see that the PR also includes the “Vonlontary basis” [sic] statuses mentioned in the above post.

**Comment by PetyaKangalova** [comment]
@akmiller01  yes, this is what I expected with the extra attributes. Let's look at Andy's comment and will review on Tuesday :)

**Comment by PetyaKangalova** [comment]
February changes have now gone live on the IATI website so closing this issue. Will create a new one for the May changes.
