### ISSUE TITLE
Update DAC codelist- May 2020

### ISSUE THREAD

**Issue by PetyaKangalova** [IATI/IATI-Codelists-NonEmbedded#328]
@akmiller01  adding the link to the latest DAC updates: https://discuss.iatistandard.org/t/notification-iati-codelists-aligned-with-oecd-dac-codelist-last-updated-28-feb-2020/1948/5

To review change later this month as the priority now is work on the website.

**Comment by akmiller01** [comment]
Hi @PetyaKangalova are you actually able to find the XML for the May 5 update? Following the links from that discussion lead me to this FTP server, which only contains the XML updated as of Feb 24: https://webfs.oecd.org/crs-iati-xml/Lookup/

**Comment by PetyaKangalova** [comment]
@akmiller01  just got in touch and will update here. It seems to me that in the Excel file there is only one addition in the channel codelist, but will wait for OECD to update the XML and confirm if there have been other changes. Thanks!

**Comment by akmiller01** [comment]
Thanks @PetyaKangalova . From the OECD's reply it sounds like only regional groupings have been updated? And regions aren't provided in XML?

**Comment by PetyaKangalova** [comment]
@akmiller01 yes, correct. Valerie confirmed that there has been one change in the May update under "Channel codes" (see below). However, the new code has not yet been pulled to the XML codelist. Once the XML codelist has been updated, then we can make the change. For now will put this issue on hold.

> The proposal to add the International Agency for Research on Cancer (IARC) to the List of ODA-eligible international organisations (Annex 2) with an ODA coefficient of 51%, in the channel category “United Nations agencies, funds and commissions” (channel category 41000), has been approved.  The channel code assigned to IARC is 41151 and the decision takes effect immediately for 2020 reporting on contributions made in 2019.

**Comment by akmiller01** [comment]
PR here @PetyaKangalova https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/329

**Comment by andylolz** [comment]
> And regions aren't provided in XML?

Given [IATI replicates the region codelist](http://reference.iatistandard.org/203/codelists/Region/), it should either be included in the DAC’s XML, or IATI should update from elsewhere.

**Comment by akmiller01** [comment]
Thanks @andylolz just pushed a commit replicating the Region codelist from the DAC XLS download: https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/329/commits/5213889b2adffcd287b5c8ccb0111d28db0abd7a

I have marked withdrawal and activation dates as 2020-05-04 since that is the date of the XLS and XML files for download, but happy to amend if that should be a decision date instead or if the date should be left off entirely.

**Comment by andylolz** [comment]
Great – thanks Alex.

I don’t know about the dates – that’s one for you folk.

I just got a notification that the DAC XML has now been updated btw.

**Comment by akmiller01** [comment]
Appears related PR is merged https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/329
