### ISSUE TITLE
Update url for National Taxonomy for Exempt Entities (USA)

### ISSUE THREAD

**Issue by notshi** [IATI/IATI-Codelists-NonEmbedded#336]
The current URL for [Sector Vocabulary Code 5](https://iatistandard.org/en/iati-standard/203/codelists/sectorvocabulary/#codes) points to http://nccs.urban.org/classification/NTEE.cfm.
This gets redirected to a search page and not a codelist.

The updated URL should be https://nccs.urban.org/publication/irs-activity-codes.

This is derived from the first search result - [National Taxonomy of Exempt Entities (NTEE) Codes ](https://nccs.urban.org/project/national-taxonomy-exempt-entities-ntee-codes).

**Comment by andreaszenasidi** [comment]
Pull request https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/341

**Comment by andreaszenasidi** [comment]
The change was implemented.
