### ISSUE TITLE
Update url for SDG Goal, SDG Target, SDG Indicator

### ISSUE THREAD

**Issue by notshi** [IATI/IATI-Codelists-NonEmbedded#338]
The current URL for [Sector Vocabulary Code 7, 8 & 9](https://iatistandard.org/en/iati-standard/203/codelists/sectorvocabulary/#codes) and [Indicator Vocabulary Code 9](https://iatistandard.org/en/iati-standard/203/codelists/indicatorvocabulary/#codes) point to external sources when they could point to IATI replicated codelists.

**Sector Vocabulary**
Code 7 SDG Goal - http://reference.iatistandard.org/codelists/unsdg-goals/
Code 8 SDG Target - http://reference.iatistandard.org/codelists/unsdg-targets/
Code 9 SDG Indicator - http://reference.iatistandard.org/codelists/unsdg-targets/

**Indicator Vocabulary**
Code 9 UN Sustainable Development Goals (SDG) Indicators - http://reference.iatistandard.org/codelists/unsdg-targets/

**Comment by andreaszenasidi** [comment]
@notshi Thanks for raising this. The [tag vocabulary](https://iatistandard.org/en/iati-standard/203/codelists/tagvocabulary/) URLs were updated but these ones were missed somehow. We will change the URLs shortly.

**Comment by andreaszenasidi** [comment]
Pull request https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/341

**Comment by andreaszenasidi** [comment]
The change was implemented.
