### ISSUE TITLE
On registration agency list, public databases aren't easily findable

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Codelists-NonEmbedded#37]
The URL field tends to be the organisation's main page, when it probably should be a more specific page about the database.

**Comment by hayfield** [comment]
@IATI/bas Is this now under the remit of org-id?

**Comment by amy-silcock** [comment]
Yes. This is now under the remit of org-id.guide. We will be replicating the codes and information about the agencies from them.
