### ISSUE TITLE
Add usage notes and an example identifier to OrganisationAgency codelist

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists-NonEmbedded#44]
It will be useful to include an example ID for an entity that references any agency.  This is because some identifiers include characters such as `-`.

For example, the South Afican NPO office has identifiers 

http://www.npo.gov.za/PublicNpo/Npo

eg: `061-870 NPO` - identifying this publisher: http://iatiregistry.org/publisher/sacbc

The published identifier is `ZA-NPO-061-870`, which:
- removes the trialing NPO
- maintains the identifier as `061-870`

It would be useful to include this in the codelist table

**Comment by hayfield** [comment]
@amy-silcock Can you advise on the current guidance situation around this?

**Comment by amy-silcock** [comment]
As this is now covered by org-id I am closing this issue.
