### ISSUE TITLE
Add ES-DIR3 for Spain to OrganisationRegistrationAgency codelist

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists-NonEmbedded#47]
Re: http://support.iatistandard.org/entries/70897189-Organisational-Identifier-Spain

NB: clarification point needed on whether DIR should be used over DIR3

**Comment by caprenter** [comment]
Re-assigning to @stevieflow until clarification as to what is actually to be used is found.

**Comment by stevieflow** [comment]
@caprenter - confirmed that this is DIR3
