### ISSUE TITLE
Pull US NGA codes from source programattically

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Codelists-NonEmbedded#53]
[LocationType](http://iatistandard.org/codelists/LocationType/) - 
http://geonames.nga.mil/namesgaz/

This should include withdrawn codes, see the approach for other codelists at https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/51

(I'm not currently sure how/when this list changes. If it hasn't changed recently, we may want to give this issue a very low priority. Compare to ISO Language - https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/8#issuecomment-72883166)

**Comment by amy-silcock** [comment]
Closing as no work has commenced since 2015.
