### ISSUE TITLE
Add Bitcoin (code XBT) to currency list

### ISSUE THREAD

**Issue by rory09** [IATI/IATI-Codelists-NonEmbedded#72]
As agreed by the IATI technical team and following no objection from the IATI Google Group mailing list.

Full details here: http://support.iatistandard.org/entries/82460089-Add-Bitcoin-code-XBT-to-currency-list

**Comment by stevieflow** [comment]
Dont forget the changelog: https://github.com/IATI/IATI-Guidance/issues/220
