### ISSUE TITLE
Look into including historical data in non-embedded codelists

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Codelists-NonEmbedded#9]

**Comment by Bjwebb** [comment]
As far as I'm aware, the development work on this issue is done. However, it needs to be reviewed and consulted on, see this pull request https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/51

**Comment by amy-silcock** [comment]
Closing this issue as no work has been done since 2015.
